### ISSUE TITLE
R -> C++ (via Rcpp) -> R (via RInside)  - not allowed ? getting "R is already initialized"

### ISSUE THREAD

**Issue by ericjb** [eddelbuettel/rinside#11]
I have a project where the top level is R which calls C++ code (using Rcpp). (This works great.)
As the C++ side has grown I now have a situation where it would be convenient within an existing C++ function to call an R function to perform a calculation. I tried using RInside but the first call to RInside fails with the message "R is already initialized". (I can reproduce this on a tiny example.)
Is this level of R / C++ / R nesting allowed somehow? Or does  one have to return from C++ to the R caller to invoke R functions.
Thanks for any guidance.

**Comment by eddelbuettel** [comment]
If I understand correctly what you are saying (and you Subject: is nicely explicit) then you seem to misunderstand what RInside is for.  

Look more closely at the RInside documentation about it does.

As for calling an R function from C++ when called from R, see `Rcpp::Function()` described all the way back in the "Introduction to Rcpp" vignette/paper and many other places.

**Comment by ericjb** [comment]
Thanks for the quick response Dirk and the pointer to Rcpp::Function(). I reviewed the relevant section in your book "Seamless R and C++ Integration with Rcpp". All good. Much apppreciated.
