### ISSUE TITLE
Rinterface.h : no such file or directory

### ISSUE THREAD

**Issue by FraDiavolo7** [eddelbuettel/rinside#12]
Hi,

We (me, and 2 others coders) are trying to embebed RInside and Rcpp to call R functions into a C++ application. This is just a preparatory work to add more functionnalities around the code as the project advances.

First of all, we made a first program to just call an R function with all the needs for the R part of the final program. I place here all the code, but I think a shorter version should be enough as the problem is only occuring in the compilation part.

```c++
#include <iostream>
#include <string>

#include "RInside.h"
#include "Rcpp.h"

using std::cout;
using std::endl;
using std::string;

int main(int argc, char *argv[]) {

	SEXP ans;
    RInside R(argc, argv);                      // create an embedded R instance

    if (argc < 4) {
            std::cerr << "Usage: " << argv[0] << " InputFilename  OutputResult RejectIntensity MaxRejectRate" << std::endl;
            return 1;
        }
    std::string input_filepath  = argv[1];
    std::string output_filepath = argv[2];
    std::string reject_intensityStr = argv[3];
    std::string max_reject_rateStr  = argv[4];
    int reject_intensity = atoi(reject_intensityStr.c_str());
    float max_reject_rate= atof(max_reject_rateStr.c_str());

    std::cout << "OK" << input_filepath << " + " << output_filepath << " + " << reject_intensity << " + " << max_reject_rate << "OK" << std::endl;

    R["input_filepath"]   = input_filepath;
    R["output_filepath"]  = output_filepath;
    R["reject_intensity"] = reject_intensity;
    R["max_reject_rate"]  = max_reject_rate;

    std::string createFunction = "TAG.demo = function(input_filepath,output_filepath,reject_intensity,max_reject_rate){"
    		"data=read.csv(input_filepath, header=T, sep=\",\");"
			"Y.id  =  data[,1];"
			"Y     =  data[,-1];"
			"Y.new =  (Y+max_reject_rate)*reject_intensity;"
			"TAG.AB_index = apply(Y.new,1,sum);"
			"TAG.Outlier = (TAG.AB_index >= quantile(TAG.AB_index,0.9))*1;"
			"Result = cbind(Y.id,Y.new,TAG.AB_index,TAG.Outlier);"
			"data.names = names(data);"
			"Result.names = c(data.names[1],paste(data.names[-1],\".TAG.Contribution\",sep=\"\"),\"TAG.AB_index\",\"TAG.Outlier\");"
			"names(Result) = Result.names;"
			"write.table(Result,file = output_filepath,row.names = F,col.names = T,sep=\",\",dec=\".\");"
			"system(paste(\"gzip\",output_filepath,sep=\"\"))}";
    R.parseEvalQ(createFunction);

    std::string commande = "TAG.demo(input_filepath, output_filepath, reject_intensity, max_reject_rate)";
    R.parseEval(commande);

    return 0;
}
```

This code is compiled under Eclipse CDT, using MinGW64 on Windows 7 64bits..

Just to be sure, here is one of the compilation command.
> g++ "-IF:\\R\\R-3.1.2\\library\\RInside\\include" "-IF:\\R\\R-3.1.2\\include" "-IF:\\R\\R-3.1.2\\library\\Rcpp\\include" -O3 -Wall -c -fmessage-length=0 -m64 -o "src\\TagDemo.o" "..\\src\\TagDemo.cpp" 

This compilation works fine. But, as soon as I add the "-std=c++11" to it, there comes the problems

> g++ "-IF:\\R\\R-3.1.2\\library\\RInside\\include" "-IF:\\R\\R-3.1.2\\include" "-IF:\\R\\R-3.1.2\\library\\Rcpp\\include" -O3 -Wall -c -fmessage-length=0 -m64 -std=c++11 -o "src\\TagDemo.o" "..\\src\\TagDemo.cpp" 
> In file included from F:\R\R-3.1.2\library\RInside\include/RInside.h:26:0,
>                  from ..\src\TagDemo.cpp:12:
> F:\R\R-3.1.2\library\RInside\include/RInsideCommon.h:56:26: fatal error: Rinterface.h: No such file or directory
>    #include <Rinterface.h>

It seems that, somehow, the macro WIN32 is not defined in the RInsideCommon.h file, but strangely, if I add a manual (and dirty) definition of WIN32 before anything in the source file, the compilation goes.

```c++
#ifndef WIN32
#define WIN32 _WIN32
#endif
```

Is there a better solution for this problem, or maybe a way to use the system defined _WIN32 macro in RInside?

Thanks for your time...

**Comment by eddelbuettel** [comment]
I'll take a look.  This simply may not have been tried with C++11 defined.

**Comment by eddelbuettel** [comment]
This appears to be a Windows issue.  When I just add `-std=c++11` to `CXXFLAGS` in the normal `GNUMakefile` builds proceed.

As I cannot test on Windows, I would appreciate a suggestion, preferably tested, for a patch.  I'll take a look at the code too, but as I cannot test (easily) on Windows some help would be appreciated.

**Comment by eddelbuettel** [comment]
Closing this as it appears to be a local issue.

**Comment by eddelbuettel** [comment]
Sorry about coming back to a really old issue -- I just hit the same error with another package of mine, looked more closely and realized that `Rinterface.h` is a Unix-only (!!) header.  So we would have to protect it by `#if !defined(_WIN32)` or alike and not unconditionally including it.
