### ISSUE TITLE
ld: 1 duplicate symbol for architecture x86_64

### ISSUE THREAD

**Issue by rnfc** [eddelbuettel/rinside#13]
Dirk,

From my Mac Terminal I re-installed Rcpp and RInside as you suggested in http://stackoverflow.com/questions/6880771/g-ld-cant-find-rinside-symbols-for-x86-64-architecture. But now I get the error: "ld: 1 duplicate symbol for architecture x86_64" when I try: make rinside_sample0. 

I do thank you in advance.
nico

**Comment by eddelbuettel** [comment]
I have no idea, but no code changed and `RInside` still works as promised. On my Linux box rebuilding  the first example:

```{sh}
edd@max:~/git/rinside/inst/examples/standard(master)$ make rinside_sample0
ccache g++ -I/usr/share/R/include -I/usr/local/lib/R/site-library/Rcpp/include -I/usr/local/lib/R/site-library/RInside/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -O3 -Wall -pipe -Wno-unused -pedantic -Wall    rinside_sample0.cpp  -Wl,--export-dynamic -fopenmp  -L/usr/lib/R/lib -lR -lpcre -llzma -lbz2 -lz -lrt -ldl -lm  -lblas -llapack  -L/usr/local/lib/R/site-library/RInside/lib -lRInside -Wl,-rpath,/usr/local/lib/R/site-library/RInside/lib -o rinside_sample0
edd@max:~/git/rinside/inst/examples/standard(master)$ ./rinside_sample0 
Hello, world!
edd@max:~/git/rinside/inst/examples/standard(master)$ 
```

**Comment by rnfc** [comment]
Thanks Dirk for your support. I found an article that explains the cause of the error type "duplicate symbol for ...": http://samwho.co.uk/blog/2013/12/08/duplicate-symbol-what/

I will work this weekend on it and get back to you. 
nico

**Comment by eddelbuettel** [comment]
I do not think that article is what you need. The article is about sorting out your code -- but RInside in general does not have that issue, ie it does not come up for me or others, nor for CRAN in their testing.

**Comment by rnfc** [comment]
Thanks for the feedback. Below is the exact output when I run make rinside_sample0
g++ -arch x86_64 -I/Library/Frameworks/R.framework/Resources/include -I/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include -I/Library/Frameworks/R.framework/Versions/3.2/Resources/library/RInside/include -mtune=core2 -g -O2 -Wall -I/usr/local/include   rinside_sample0.cpp    -F/Library/Frameworks/R.framework/.. -framework R -lpcre -llzma -licucore -lm -liconv  -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/Library/Frameworks/R.framework/Resources/lib -lRlapack  /Library/Frameworks/R.framework/Versions/3.2/Resources/library/RInside/lib/libRInside.a -o rinside_sample0


duplicate symbol _R_running_as_main_program in:
    /var/folders/1k/jn55_g3x2jdb653wspftm3vc0000gn/T/rinside_sample0-546ad7.o
    /Library/Frameworks/R.framework/Versions/3.2/Resources/library/RInside/lib/libRInside.a(RInside.o)
ld: 1 duplicate symbol for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
<builtin>: recipe for target 'rinside_sample0' failed
make: *** [rinside_sample0] Error 1

**Comment by eddelbuettel** [comment]
Maybe someone on the r-sig-mac list can help.  Somehow the linking / building process now leaves a symbol in there twice.   But also note that you compile with g++ but link with clang which is a little suspicious.

**Comment by rnfc** [comment]
Dirk I tried changing the link to the GNU Compiler Collection but still getting the same error:

ld: 3 duplicate symbols for architecture x86_64
collect2: error: ld returned 1 exit status

I will keep working on the book. I already finished revising and making some minor changes to some examples. I replicated all of them using markdown and it has been a fantastic learning curve. Let me know which email I should use to send it to you and/or if you already set up the errata page.

**Comment by eddelbuettel** [comment]
Wow, that's terrific.  My usual email works, and I don't have a repo yet for the book.

**Comment by rnfc** [comment]
Dirk got it. The problem using make on a mac is that the function RInside:::LdFlags() is printing ..../library/RInside/lib/libRInside.a and it should be ..../library/RInside/lib/libRInside.dylib.
What email should I use? your debian.org?

**Comment by eddelbuettel** [comment]
Strange. But easy to change.  Please discuss with Simon and others, in fact: please discuss on rcpp-devel (where you need to subscribe to post if you're not yet subscribed).

RInside is not a new project; this all worked for years.  I still don't whether you did something unusual at your end, or whether Simon changed the build for OS X and RInside needs to change to.   But you can test this locally -- and maybe then report to rcpp-devel. 

And yes, the maintainer address on the package works as it supposed. It is the same address given for me everywhere else.

**Comment by rnfc** [comment]
Dirk it was a great pleasure to finally meet you. I am currently revising all the changes in the book so I can send you the markdown files with the source code to compile and run the examples on each chapter.

Finally I realized that to Makefile directly from RStudio I have to set the working directory to the example folder. If I try to do: 

make /Library/Frameworks/R.framework/Versions/3.2/Resources/library/RInside/examples/standard/rinside_sample6

it wont work; It says RInside.h not found.

but if I do:

setwd(file.path(RINSIDE_PATH, "examples", "standard"))
cat(system("make rinside_sample0", intern = TRUE), sep="\n")

It works!

The only missing piece is to set up the default compiler / link to gcc on RStudio rather than having clang. 
Since R install defaults to clang instead of gcc, I had to make the changes on the Makeconf and it works. But on RStudio I still get: system('g++ -v') 

Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix


Again thank you so much.

nico

**Comment by eddelbuettel** [comment]
Nice to meet you too.

I always do that in the shell, and I copy the `examples/` to something like `/tmp/rinside` to `~/projects`.  And saying just `make` in a terminal windows is much simpler, in my eyes....

**Comment by rnfc** [comment]
Agreed 100%. But remember that the audience are my students and I am creating a high performance course with R and C++ with application in trading. I am 50% done with the material for the C++ syntax and to design, code and backtest the strategies I am planning to incorporate in the course Rcpp and RcppParallel. If they go through the book without the source code to replicate the examples they will struggle  trying to figure out how to apply the material. For example, most of the examples in the chapter on Sugar were easy since you used SourceCpp but the other chapters were challenging since it lack the lines of code for compiling. If we provide the markdown of the examples and they have the printed version of the book then they can . It helped me a lot going back and forward between cheap chapter on the book and the test folders on your repository.

**Comment by eddelbuettel** [comment]
:+1: 

This will be good to have.  Maybe we even keep it in GitHub in Markdown.

**Comment by eddelbuettel** [comment]
Is there still a buildability issue?

**Comment by rnfc** [comment]
Was able to get it working by doing:

pkg_url <- "http://cran.r-project.org/bin/macosx/mavericks/contrib/3.1/RInside_0.2.13.tgz" install.packages(pkg_url, repos = NULL)

I am finishing Ch 12 since I was missing the case study and had to change some of the examples to make it reproducible (eg., C call to "fastlm" to "RcppGsl_fastLm" same for armadillo in the benchmark example.

Below is the link to the dropbox folder with all the markdown to reproduce each example, or if you can give me u ntil tomorrow i can send you the tar file with the html folder as well.

https://www.dropbox.com/sh/yb73r3w3zwftrmd/AADgrSa954JBTt67qYGItoF1a?dl=0

Sorry for the delay but completely forgot that I was missing to finish Ch 12.

PS. Do you think is a good idea to connect Yi with Joshua for the parallel version of RcppDe? Also professor Norman Matloff and JJ can provide guidance on tricks we can use for OpenMP. Let me know your thoughts.

Nico

**Comment by eddelbuettel** [comment]
Ok, good,  Will close this.

Will reply by email to the other conversation which has nothing to do with the ticket.
