### ISSUE TITLE
rinside gives compiler warnings when compiling with G++ and -Weffc++ flag

### ISSUE THREAD

**Issue by richelbilderbeek** [eddelbuettel/rinside#15]
When compiling with GCC 4.9.2 under Lubuntu 15.04 and the -Weffc++ warning flag (which adds the advices given in Scott Meyers' book 'Effective C++') many warnings pop up. 

Example warnings are:
 * unused parameters
 * member variables that should be initialized (probably to zero) in the initializer list
 * classes having pointer data members, yet the copy constructor and assignment operator are not either forbidden or written

I do volunteer to do the grunt work to add these (rather trivial) fixes (I think RInside is great!) as it makes me keep compiling at the highest warning level.

**Comment by eddelbuettel** [comment]
Please do.  

My go-to setting is 

    CXXFLAGS += -O3 -Wall -pipe -Wno-unused -pedantic

but I could be convinced rather easily to escalate to `-Weffc++`.   Just bear in mind that a good chunk may be coming in from Rcpp as well...

**Comment by richelbilderbeek** [comment]
I'll submit a pull request within a few days.

**Comment by eddelbuettel** [comment]
:+1:

**Comment by richelbilderbeek** [comment]
> Just bear in mind that a good chunk may be coming in from Rcpp as well...
You were right, I will move this issue to the Rcpp GitHub.

**Comment by eddelbuettel** [comment]
Cool. Bigger code base, more widely used. Also more eyes on it.  Please document clearly which compiler version and which switches you use so that we can follow along.
