### ISSUE TITLE
Including installed R packages

### ISSUE THREAD

**Issue by NoahMarconi** [eddelbuettel/rinside#18]
Hi, sorry if I'm missing something obvious but I can't see how to install packages to embed as well.

What I'm trying to do is embed within an AWS lambda function. Are there particular steps I need to take to include installed R packages?

**Comment by eddelbuettel** [comment]
Just think it through for a second:  It is _the same R installation_ so just install packages as usual.  RInside will find and use them (unless you create an egg with bad settings of `.libPaths()`).  Some of the included examples use `library(....)` as well.
