### ISSUE TITLE
Problem with dyn.load

### ISSUE THREAD

**Issue by felipedevargas** [eddelbuettel/rinside#19]
Hi, i try to create an interfaces for Fortran calling R functions using Rinside, create an shared object and when i use dyn.load to load my library R simply closes.

**Comment by eddelbuettel** [comment]
Please consider preparing a [minimally reproducible example](http://stackoverflow.com/questions/5963269).

As a generality, I suggest creating a package.  The discipline this imposes will likely pay itself back with interest as this should then 'just work' with RInside as we had examples using `library(foo)` for many many years.  RInside simply starts an R instance for you.  If something goes belly-up it may well be your code.

**Comment by felipedevargas** [comment]
Thank you i found the error....

**Comment by eddelbuettel** [comment]
No worries.
