### ISSUE TITLE
Problem with dyn.load R package

### ISSUE THREAD

**Issue by felipedevargas** [eddelbuettel/rinside#20]
Hi.
I have this code in my R package.

void test(){
    RInside R(0, NULL);

}
but when I use the function using .Call("test") return's R is already initialized
> dyn.load("test.so")
> .Call("test")
R is already initialized

Any idea? can I call code's that uses Rinside direct  from R?

**Comment by eddelbuettel** [comment]
You misunderstand what RInside is for.  See the eight (!!) examples subdirectories: in _all_ cases do we build _standalone binaries with a `main()`_ and in _no case whatsoever_ do we get called from R.
