### ISSUE TITLE
64bit vs 32bit RInside on windows 64bit machine

### ISSUE THREAD

**Issue by MSCypher** [eddelbuettel/rinside#23]
I am writing a C++ program that uses RInside on Windows 7 64bit or 64bit servers. Everything works fine on small datasets, but fails on large datasets. For example, the amount of memory available is 16Gb on my PC (windows 7), but RInside is reporting a 2047Mb limit (32 bit). Can I explicitly within my C++ code invoke an instance of RInside and specify the maximum amount of memory available? Or do I need to tweak compilation settings for RInside? The former is preferred over the latter for workflow automation for external users.

We are moving to linux but it is a gradual process due to the fact that we have explicit windows executables as part of a workflow.

Thank you in advance
Eugene

Example session info is as follows:

> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252   
[3] LC_MONETARY=English_Australia.1252 LC_NUMERIC=C                      
[5] LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] RInside_0.2.13       BiocInstaller_1.22.1

loaded via a namespace (and not attached):
[1] tools_3.3.0   Rcpp_0.12.4.5

**Comment by eddelbuettel** [comment]
You say

> RInside is reporting a 2047Mb limit (32 bit)

How? Ie what are you executing?

I did a quick check and see no `R_len_t` use which could limit us.  If you have some reproducible, I could test it on one of the huge honking servers at my work tomorrow.

**Comment by MSCypher** [comment]
Hi Dirk,
I realise that I could use Rscript for this example, but I would like to
explore and use RInside, Rcpp in the future. That said I am providing the
cpp file that I compiled using the latest Rtools plus makefile.win. The
executable is provided with a config file which points to the R script to
run. When I run the R script within R it correctly shows the amount of
memory available (in my case 16Gb), however when I run this executable
(RscriptWrapper) from the command line on Windows 7 64bit it outputs
2047Mb. Perhaps the issue lies with the makefile.win which I modified
slightly to use C++ 11 (I think).

The above example is purely for illustration but we have Random Forest
wrappers that read 60Gb files and bigger - machine learning etc. for
scientific research in medical applications. I am relatively new to RInside
so if there are trivial errors/issues please let me know.

Thanks
Eugene

On Mon, May 16, 2016 at 12:26 PM Dirk Eddelbuettel <notifications@github.com>
wrote:

> You say
>
> RInside is reporting a 2047Mb limit (32 bit)
>
> How? Ie what are you executing?
>
> I did a quick check and see no R_len_t use which could limit us. If you
> have some reproducible, I could test it on one of the huge honking servers
> at my work tomorrow.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eddelbuettel/rinside/issues/23#issuecomment-219335974>
>

// Copyright (C) 2009 Dirk Eddelbuettel 
// Copyright (C) 2010 Dirk Eddelbuettel and Romain Francois
// Eugene Kapp and Keith Satterley (2016)

#include <RInside.h>                    // for the embedded R via RInside
#include <Rcpp.h>

#include <string>
#include <algorithm>
#include <vector>
#include <fstream>
#include <istream>
#include <iostream>
#include <sstream>
#include <streambuf>

using namespace::std;

struct EmbeddedRMLParams {			// for storing config information
	string		strFile;				// Rscript input file
};

string read_file_as_string(const std::string &filename);
bool GetParams(const vector<string>&, EmbeddedRMLParams& params);

#if defined(RINSIDE_CALLBACKS)
class MyCallbacks : public Callbacks {
    public:
        // see inst/includes/Callbacks.h for a list of all overrideable methods
        virtual void WriteConsole( const std::string& line, int type ) {
            output_buffer << line << std::endl;
        };

        virtual bool has_WriteConsole() {
            return true;
        };

        std::string getConsoleOutput() {
            return output_buffer.str();
        }
    private:
        std::ostringstream output_buffer;
};
#endif

std::string read_file_as_string(const std::string &filename)
{
	std::string contents = "";
	std::ifstream input(filename, std::ios::in | std::ios::binary);
	if (input)
	{
		input.seekg(0, std::ios::end);
		contents.resize(input.tellg());
		input.seekg(0, std::ios::beg);
		input.read(&contents[0], contents.size());
		input.close();
	}
	return contents;
}

bool GetParams(const vector<string>& vstrInput, EmbeddedRMLParams& params)
{
	basic_string <char>::size_type startIndex;
	bool bOK = false;
	bool bSection = false;
	bool bKey = false;

	// find section [RScript] and key is File=
	for (auto it = vstrInput.begin(); it != vstrInput.end(); ++it)
	{
		if (bSection && bKey)
		{
			bOK = true;
			break;
		}

		if (!bSection && (startIndex = it->find("[RScript]")) != string::npos)
			bSection = true;

		if (!bKey && (startIndex = it->find("File=")) != string::npos)
		{
			params.strFile = it->substr(startIndex + 5);
			bKey = true;
		}
	}

	if (bSection && bKey)
		bOK = true;
	else
		bOK = false;

	return bOK;
}

int main( int argc, char *argv[] )
{
    // Check cmdargs before proceeding
	if (argc != 2)
	{
		// Notify user of expected command line arguments
		cout << "Program needs 2 arguments" << endl;
		exit(0);
	}
	
	RInside R(argc, argv, true, true, true);          // create an embedded R instance	
	
    #if defined(RINSIDE_CALLBACKS)
    R.set_callbacks( new Callbacks() );
    R.repl() ;
    #endif
    	
	//MyCallbacks *callbacks = new MyCallbacks();	

	
	//R.set_callbacks( callbacks );
	cout << "Running RscriptWrapper..." << endl;

	string strLine;
	vector<string> vRMLInput;
	string filePath = argv[1];
	ifstream configFile(filePath);

	if (!configFile.bad())
	{
		// Read in R ML ini configuration settings
		while (getline(configFile, strLine))
			vRMLInput.push_back(strLine);
	}
	else
	{
		cout << "Cannot access the configuration file or it does not exist" << endl;
		exit(0);
	}
	
	cout << "Getting parameters..." << endl;
	
	// 1st check all the input files and workflow
	EmbeddedRMLParams dParams;
	if (!GetParams(vRMLInput, dParams))
	{
		cout << "Failed to read config file..." << endl;
		exit(0);
	}
    
    cout << "Reading R script file..." << endl;
	std::string txt = read_file_as_string(dParams.strFile);
	
	// sanity checks
	if (txt.empty())
	{
		cout << "There is no text in the R script file. Please check and try again!" << endl;
		exit(0);
	}
    
    R.assign(txt, "txt");
    R.parseEvalQ(txt);                 // eval command, no return
    //std::string result = callbacks->getConsoleOutput();
	//printf("R said:\n%s\n", result.c_str());
	
	exit(0);
}

**Comment by eddelbuettel** [comment]
Ok, that was _not_ really helpful.  The code is long, builds only if one adds `-std=c++11` (so it does _not_ fit into `examples/standard/` as is, and requires a configuration file you did not ship.  Nor did you show the invocation.

Can you please focus on providing a [minimally reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example)?

**Comment by MSCypher** [comment]
Dirk,

OK. I have changed 2 lines within "rinside_sample0.cpp" and compiled using
your Makefile.win provided with RInside. This was compiled using the latest
Rtools and R3.3.0 on a windows 7 64bit machine.

From the windows command prompt the output is: 2047

The lines of code are as follows:

 int main(int argc, char *argv[])
{
    RInside R(argc, argv, true, true, true);              // create an
embedded R instance

    std::string txt = "memory.limit()";
    R.assign(txt, "txt");
    R.parseEvalQ(txt);           // eval the init string, ignoring any
returns
    exit(0);
}

Thanks and apologies for the delay getting back to you.
Eugene


On Tue, May 17, 2016 at 1:12 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by MSCypher** [comment]
Dirk,

As a follow up - when I add the memory.limit() to an R file and run this
from the windows command prompt using the Rscript executable (within
R3.3.0\bin\x64) I get the correct memory: 16340.

Hope this helps troubleshoot.
Thank you
Eugene

On Tue, May 17, 2016 at 1:12 AM, Dirk Eddelbuettel <notifications@github.com

**Comment by eddelbuettel** [comment]
`memory.limit()` is a Windows-specific functions, see `help(memory.limit())`. 

There is nothing RInside can do here. you will get _the same value when you run the function in Windows directly in R_.

**Comment by MSCypher** [comment]
When I run the same function in Windows directly in R I get 16340
Clearly there is a an issue with RInside on Windows.

Not very helpful

**Comment by eddelbuettel** [comment]
Can you please try to debug? 

The simplest case I can think of is that your 'Windows directly' hits the 64bit executable whereas RInside may be built against 32 bit?  Otherwise we _clearly_ do not limit anything on purpose.

**Comment by eddelbuettel** [comment]
FYI:

```
R> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: i686-pc-linux-gnu (32-bit)
Running under: Ubuntu 16.04 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] fortunes_1.5-2
R> system("free")
              total        used        free      shared  buff/cache   available
Mem:        3828732     1985352      211856      342428     1631524     1434376
Swap:       3883004     1341940     2541064
R> memory.limit()
[1] Inf
Warning message:
'memory.limit()' is Windows-specific 
R> 
```
