### ISSUE TITLE
libRInside.so has no SONAME

### ISSUE THREAD

**Issue by luigino** [eddelbuettel/rinside#24]
As per subject, it complicates packaging on some distros.

Regards

**Comment by eddelbuettel** [comment]
No it doesn't. I have also been its package maintainer in Debian for roughly a decade.

The .so file is only loaded by R, and `ldconfig` et al do not know about it.

**Comment by eddelbuettel** [comment]
Or in other words:  if you have _local_ issues on a distro, just patch it locally on that distro.
