### ISSUE TITLE
RInside can't be initialized on child thread 

### ISSUE THREAD

**Issue by assassin5615** [eddelbuettel/rinside#30]
not sure if this is intended behavior. but it seems weird. I understand that R does not support multi thread. But creating RInside on a child thread, and use it on this child thread only should be fine as it is used on a single thread. 

however, with following code, I always got the "Stack usage is too close to the limit" error.

void create_R()
{
    printf("create R\n");
    RInside r(0, nullptr);
    printf("r created\n");

}

int main(int argc, char** argv)
{
    std::thread t(create_R);
    t.join();
    return 0;
}

it seems that RInside can only be created on main thread which is a surprise.

**Comment by eddelbuettel** [comment]
RInside is really just convenience code against the _already existing C API of R_ so you should expand your and see if/where that constraint arise.  

We don't set any locks, or affinities, or ... so I suspect it is due to R.  But yes, it is known behaviour.

**Comment by assassin5615** [comment]
Thanks for the explanation
