### ISSUE TITLE
3rd Party Library Installation

### ISSUE THREAD

**Issue by batuhanaman** [eddelbuettel/rinside#37]
Hi,

Sorry if this question does not make sense. I want to learn if I can use RInside to install 3rd party R libraries (for example from Github)? Or, do I need to code the 3rd party library from scratch? Thanks for your understanding.

**Comment by eddelbuettel** [comment]
You do not need RInside to install from CRAN.  See a standard R tutorial about how to install packages (from CRAN), once you are comfortable with that consider tje `remotes` packages (on CRAN) to install from GitHub.

I generally recommend installing from CRAN though.

**Comment by batuhanaman** [comment]
Hi, thanks for your prompt response. Actually, I have a C++ code and I want to call 3rd party R packages from C++ via RInside.  I successfully run the 3rd party library on R Studio. Now I want to transfer this 3rd party library inside the C++ via RInsider. Thanks for your directions and information.

**Comment by eddelbuettel** [comment]
I am sorry but I can't provide one-on-one tutorials here on demand.  Maybe you could write to the rcpp-devel list which is pretty low-volume and friendly -- and covers RInside too.
