### ISSUE TITLE
Package installation issue

### ISSUE THREAD

**Issue by bug1303** [eddelbuettel/rinside#39]
Hi, 
I had tried to run `install.packages("RInside")` from within my RStudio session and ran into all kinds of warnings and errors:

```
In file included from RInside.cpp:121:0:
RInsideEnvVars.h:22:33: warning: invalid suffix on literal; C++11 requires a space between literal and identifier [-Wliteral-suffix]
         "R_SESSION_INITIALIZED","PID=24376:NAME="reticulate"",
                                 ^
RInsideEnvVars.h: In member function ‘void RInside::initialize(int, const char* const*, bool, bool, bool)’:
RInsideEnvVars.h:22:50: error: expected ‘}’ before ‘reticulate’
         "R_SESSION_INITIALIZED","PID=24376:NAME="reticulate"",
                                                  ^
RInsideEnvVars.h:22:50: error: expected ‘,’ or ‘;’ before ‘reticulate’
RInside.cpp: At global scope:
RInside.cpp:135:5: error: expected unqualified-id before ‘for’
     for (int i = 0; R_VARS[i] != NULL; i+= 2) {
     ^
[...]
```

I noticed that the issue was caused by `Sys.getenv()` returning an environment variable which contains quotes itself:
`R_SESSION_INITIALIZED         PID=24376:NAME="reticulate"`
which gets written as 
`"R_SESSION_INITIALIZED","PID=24376:NAME="reticulate"",`
into `RInsideEnvVars.h`
Apparently something used by reticulate/rpy2.

I ended up editing src/tools/RInsideEnvVars.r and added the problematic environment variable to the `ExcludeVars` as follows:

```
ExcludeVars <- c("R_SESSION_TMPDIR", "R_HISTFILE", "R_LIBRARY_DIR",
                 "R_LIBS", "R_PACKAGE_DIR", "R_SESSION_INITIALIZED")
```

With this edit, I was able to build the package successfully.

Actually, I was also able to build it from command line R, rather than Rstudio, without my edit.

Maybe environment variables containing quotes could be handled better in general. Or there could be a hint somewhere for the installation.

**Comment by eddelbuettel** [comment]
> Actually, I was also able to build it from command line R, rather than Rstudio, without my edit.

Of course.  That is how CRAN tests.  Using it from inside RStudio, with an added reticulate package, is entirely your issue.  

![image](https://user-images.githubusercontent.com/673121/70323033-61960400-17f1-11ea-975b-42d1f59eed81.png)

I am sorry you had to debug this (which you did well) but I don't think there really is an actionable issue here.  I could add the env var but then ... that really is a slippery slope.  I'd rather close, I really think it is local to your case.  _In general it is always recommended to start from a clean slate, ie the command-line_.

**Comment by bug1303** [comment]
It's fine not to do anything about this, since indeed there is no issue with the package as such, however I thought to write in here in case someone runs into a similar problem. I always find it helpful if I find such records of issues that someone else solved already when I run into the same.
You could add a note of the recommended way of installing the package, although it is the general case.

**Comment by eddelbuettel** [comment]
The real issue, I guess, are the embedded quotes.  We may be able to do something there.

**Comment by eddelbuettel** [comment]
I think I can and should make that a little more robust.  If I prepare a candidate fix, can you try installing with it (and I can prepare a tar.gz for you, of course) ?

**Comment by bug1303** [comment]
Sure, I will be happy to test it.

**Comment by eddelbuettel** [comment]
That really was a real bug that has been sitting there for a decade and more not biting anyone.  I set a local environment variable as in your example above, and it now works.  In essence, I am now calling `shQuote()` and use single quotes, which lets the inner double quote survive.

But to be sure, please check this candidate tarball in the same setting as above:
http://dirk.eddelbuettel.com/tmp/RInside_0.2.15.1.tar.gz

**Comment by eddelbuettel** [comment]
Looks like I was overly optimistic / not thorough enough with my test.  I think I may have to revert that to what it was before, but add (as you did) this reticulate/rpy2 variable to the ones we skip.

**Comment by eddelbuettel** [comment]
Also, are you sure you are not already getting it back with escaped quote? In "simulated" check I do:

```
R> Sys.setenv("R_S_I"='PID=23456:NAME="reticulate"')
R> Sys.getenv("R_S_I")
[1] "PID=23456:NAME=\"reticulate\""
R> 
```

**Comment by eddelbuettel** [comment]
I updated the tarball at http://dirk.eddelbuettel.com/tmp/RInside_0.2.15.1.tar.gz

**Comment by eddelbuettel** [comment]
Seems to work here when I force installation from RStudio in a reticulated session:

```r
R> py_run_string("print(2+2)")
4
R> Sys.getenv("R_SESSION_INITIALIZED")
[1] "PID=8405:NAME=\"reticulate\""
R> install.packages("RInside_0.2.15.1.tar.gz", repos=NULL)
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
* installing *source* package ‘RInside’ ...
** using staged installation
** libs
/usr/lib/R/bin/Rscript tools/RInsideAutoloads.r > RInsideAutoloads.h
/usr/lib/R/bin/Rscript tools/RInsideEnvVars.r   > RInsideEnvVars.h
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I. -I../inst/include/ -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O3 -Wall -pipe -pedantic  -c MemBuf.cpp -o MemBuf.o
ccache g++ -I"/usr/share/R/include" -DNDEBUG -I. -I../inst/include/ -I"/usr/local/lib/R/site-library/Rcpp/include"   -fpic  -g -O3 -Wall -pipe -pedantic  -c RInside.cpp -o RInside.o
ccache g++ -Wl,-S -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RInside.so MemBuf.o RInside.o -L/usr/lib/R/lib -lR
ccache g++ -o libRInside.so MemBuf.o RInside.o -Wl,-S -shared -Wl,-Bsymbolic-functions -Wl,-z,relro   -L"/usr/lib/R/lib" -lR
ar qc libRInside.a MemBuf.o RInside.o
cp libRInside.so ../inst/lib
cp libRInside.a ../inst/lib
rm libRInside.so libRInside.a
installing to /usr/local/lib/R/site-library/00LOCK-RInside/00new/RInside/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RInside)
R> 
```
