### ISSUE TITLE
'dataptr' not provided by package 'Rcpp' w/ RInside

### ISSUE THREAD

**Issue by jonathon-love** [eddelbuettel/rinside#44]
hi dirk,

i appreciate this is a common error message, with well documented solutions, but i haven't been able to find a solution to the following.

i've been using RInside with R 3.6.3 across macOS, linux and windows quite successfully in our application (jamovi). i've just tried updating to R 4.0.2, and everything continues to work under macOS and linux, however now i get the `'dataptr' not provided by package 'Rcpp'` error under windows.

RInside works, i'm able to evaluate R expressions, however the error takes place when i construct a RawVector
i've tried loading Rcpp via `_rInside->parseEvalQNT("base::require('Rcpp')\n");`, before constructing the RawVector (the package successfully loads) however the dataptr error persists.

any tips on a good way to move forward here?

with thanks

**Comment by jonathon-love** [comment]
found a work around ... if i load a package which does the `Imports: Rcpp` and `importFrom("Rcpp", "evalCpp")`, *before* attempting to construct a RawVector (or any other Rcpp type presumably), then it works and i don't receive the error.

surprised that that works, and `require('Rcpp')` doesn't ... you likely have more insights.

is this something you want to dig into? (i suppose you don't use windows) or is it simpler just to add a note to the docs (i'm happy to PR) ... or i suppose we could just leave this issue open.

cheers

**Comment by eddelbuettel** [comment]
I suspected that seeing the error message first from the Subject line -- I think this issue has zero to do with RInside and only with how Rcpp is initialized which requires a bit of pulling by its own boostraps. Which is what the (recommended if not required) `importFrom("Rcpp", "evalCpp:)` triggers and which is why we usually add it (or import of another symbol).

And that has been unchanged since mayne 2013...   So I think no action item here unless you can convince me of one.

**Comment by jonathon-love** [comment]
yeah, i understand. it's more that this hasn't been necessary before. it seems to me that the RInside examples provided probably won't work with R4 under windows for example -- as they don't perform any Rcpp bootstrapping.

the way i'm working around this at the moment is creating a minimal package with the appropriate `importFrom()` et al, called `RcppBootstrap`, calling `require('RcppBootstrap')`, before constructing any other Rcpp objects.

is that the best way? or is there a simpler trick? i tried `_rInside->parseEvalQNT("x <- Rcpp::sourceCpp")`, but that's not enough.

with thanks

**Comment by jonathon-love** [comment]
ah, sorry, calling `requireNamespace('Rcpp')` is sufficient to resolve this issue ... i was calling it too early in my program, before i'd set up the `.libPaths()`, Rcpp wasn't on the path, and the `requireNamespace(...)` was failing ... but i took the message output by R: "Loading package Rcpp" (or something like that) as success, when the load was actually failing.

**Comment by eddelbuettel** [comment]
Ok, closing this then.
