### ISSUE TITLE
R is already initialized using pointer of Rinside object

### ISSUE THREAD

**Issue by zhaofeng-shu33** [eddelbuettel/rinside#46]
I compile the following simple code in debian buster by
```
g++ -I/usr/lib/R/site-library/Rcpp/include -I/usr/lib/R/site-library/RInside/include -I/usr/share/R/include/ -L/usr/lib/R/site-library/Rcpp/libs/ -L/usr/lib/R/site-library/RInside/lib/ -lR -lRInside -l:Rcpp.so main01.cpp -o main01
```
```
#include <RInside.h>
int main() {
    RInside* rinside;
    rinside = new RInside();
    delete rinside;
    rinside = new RInside();
    delete rinside;
}
```
When I run the program, I get the console message "R is already initialized". I do not know which is wrong with my code.

**Comment by eddelbuettel** [comment]
This is documented (somewhere ...).  You can only have _one instance_ of `RInside` (per process) so your code is in fact wrong.

**Comment by zhaofeng-shu33** [comment]
Thanks for your suggestions.

**Comment by eddelbuettel** [comment]
`RInside` isn't exactly a brand new project so some of these things have come up before, but these days it's no longer as obvious where that was.  I once tried what you tried to, and I think I documented it as a consequence but if you found it lacking ... well sorry.  Suggestions welcome -- there are still _several dozen_ examples in the package as is.
