### ISSUE TITLE
Use HTTPS protocol for the website?

### ISSUE THREAD

**Issue by IndrajeetPatil** [eddelbuettel/rinside#49]
Otherwise, this is what I see in Chrome:

<img width="405" alt="Screenshot 2022-04-01 at 17 09 36" src="https://user-images.githubusercontent.com/11330453/161291361-0171bf7c-2017-4b37-8409-6283301ea6b8.png">

**Comment by IndrajeetPatil** [comment]
If this is built on top of GitHub pages, then it should be for free.

I have over 2 dozen package websites that use HTTPS protocol and I have paid 0 cents.

> Sure, venmo me some money for an cert

At any rate, created an issue because I thought you'd like to know about this; wasn't expecting such a response.

**Comment by eddelbuettel** [comment]
I am aware of the deficiency (how could I not be? It's my own website and has been for (if memory serves) close to 25 years), and is self-hosted (as you could have found out) so you flippant github pages comment is useless.  

I spent some time trying to automake this with let's encrypt, apparently somewhat successfully i.e. when I go to the top-level or some other pages it actually _works_.  So it could be that there are (on this fairly rarely visited page) some remaining http links as I recall chrome and other now flip the entire page back to http.  If that upsets you greatly maybe you can read the page in https via the wayback machine or the google cache.  I maintain the page, my 60+ CRAN packages, the dozen+ Rocker container and the 180+ Debian package I look after as a volunteer.  So some things may slip. 

I understand you may have helpful, but if you re-read the Subject line, the tone of your first comment _and_ the fact that https works on other pages (I dare say the majority of the site) you may realize that you did not come across as all that helpful.

Peace out.

**Comment by eddelbuettel** [comment]
Also:

![image](https://user-images.githubusercontent.com/673121/161305179-d0273f88-bd80-4d06-a182-71b45b8bc64a.png)

so not sure what is going on.

**Comment by eddelbuettel** [comment]
Also, if you followed that from somewhere, do you remember where from?   

I just noticed that DESCRIPTION still has it as http and I can update that; others in the README and other files to get flapped by the URL checker and should be current.
