### ISSUE TITLE
CMakeLists.txt Example

### ISSUE THREAD

**Issue by rspadim** [eddelbuettel/rinside#50]
Hi folks, is there an example of how to create a CMakeLists.txt file to build a c++ project with R Inside?

**Comment by eddelbuettel** [comment]
Years ago a few of the `examples/` directories received some support for `cmake`:

```
edd@rob:~/git/rinside(master)$ find . -type d -name cmake
./inst/examples/eigen/cmake
./inst/examples/wt/cmake
./inst/examples/qt/cmake
./inst/examples/mpi/cmake
./inst/examples/armadillo/cmake
./inst/examples/standard/cmake
edd@rob:~/git/rinside(master)$ 
```

Besides that you are on your own (but we have _plenty_ of examples below `inst/examples` (in the sources, below `examples/` once installed).  R projects have traditionally relied on `autoconf` and friends, you can also call R itself (starting with `R RHOME`).

**Comment by eddelbuettel** [comment]
I am going to close this as it is a little outside of our scope.  If you feel strongly that it should be open, please reopen but few (if any) R packages (or R itself) support CMake for discovery and project builds.
