### ISSUE TITLE
Qt example doesn't compile with Qt6

### ISSUE THREAD

**Issue by JorisGoosen** [eddelbuettel/rinside#53]
As even Qt5 is outdated by now and the demo is written for Qt4 it is also time to update the demo in any case.

Ive already got it to work locally and I think this can also help other people out so Ill open a PR .

**Comment by eddelbuettel** [comment]
A PR would be lovely. I haven't touched Qt in some time myself.  By chance, are you working on Ubuntu or Debian so that it would be easy-ish for me to follow along?

And plain lovely to see this being used.

**Comment by JorisGoosen** [comment]
If I get the chance to test it on linux I tend to work with Arch but with the cmake stuff it shouldnt even matter to much luckily.

**Comment by eddelbuettel** [comment]
Yes. And I have a battery of libqt6 packages installed here. I may have a chance to give it a whirl later.
