### ISSUE TITLE
unprovided class name

### ISSUE THREAD

**Issue by dusadrian** [eddelbuettel/rinside#56]
Under MacOS, I have successfully built all examples under the "standard" directory, and I am now trying to build the example "sandboxed_server". It fails with this error:
```
In file included from server/rinsideserver.cpp:9:
In file included from server/rinsideserver.h:10:
server/rinside_callbacks.h:1:33: error: expected class name
class RInsideCallbacks : public Callbacks {
                                ^
1 error generated.
```
Is there something missing in that file?

**Comment by eddelbuettel** [comment]
Can you share which compiler you used?

**Comment by eddelbuettel** [comment]
It works when you enable the optional callback support in `RInside` itself at

https://github.com/eddelbuettel/rinside/blob/2cf4094225a825d1e807461edd301a013b391fd0/inst/include/RInsideConfig.h#L23-L24

and reinstall `RInside` so that the callback support this example needs is provided.

**Comment by dusadrian** [comment]
Thanks so much, an especially for responding so quickly in a Saturday.
It works now, digging further,
Adrian

**Comment by eddelbuettel** [comment]
I now added a [README.md](https://github.com/eddelbuettel/rinside/blob/master/inst/examples/sandboxed_server/README.md) to that directory too in order to note this more prominently.
