### ISSUE TITLE
Enhance Documentation for Getting Started and Qt Application Integration

### ISSUE THREAD

**Issue by nev-awaken** [eddelbuettel/rinside#57]

**Comment by eddelbuettel** [comment]
Are you proposing a concrete improvement?  

I wrote most if this a decade or more ago, it worked, and several people used it / forked it / extended it.   If you just want to state that you don't like like the documentation, I can, as the saying goes, offer you your money back under the usual open source warranty.

**Comment by nev-awaken** [comment]
I'm proposing of an improvement to documentation. So that any beginner (like me) can get started
