### ISSUE TITLE
C++ application with RInside and its future usage dependency on local R installation

### ISSUE THREAD

**Issue by RLWOHIO** [eddelbuettel/rinside#58]
I am interested in creating a C++ application with embedded R so it can run on other users' machines which do not have local installation of R. I am not clear if this is possible with RInside/Rcpp. I have searched around and couldn't find an answer.

So far I managed to compile RInside standard examples on Ubuntu. But when running them on another Ubuntu machine without R installed, I got error messages saying the R shared library(libR.so) is not found.  This seems to imply that, if I link a R static library to a C++ program instead, then it can be run on another machine which does NOT need to have a local R installation. 

Am I getting this right? If so, how can I create a static R library using RInside/Rcpp somehow and link it to a C++ program? Or else I have to resort to Rtools to create such a static library from source beforehand and then make it available to RInside?

Thanks in advance!

**Comment by eddelbuettel** [comment]
You _of course_ must have R installed to use RInside: that is how shared libraries work.
